# Default application configuration that all configurations inherit from.

scss_files: "**/*.css"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: false

  Comment:
    enabled: true
    style: silent

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: false
    max_depth: 3
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: true

  PrivateNamingConvention:
    enabled: false
    prefix: _

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertySortOrder:
    order:
    - position
    - top
    - right
    - bottom
    - left
    - z-index
    - display
    - float
    - width
    - min-width
    - max-width
    - height
    - min-height
    - max-height
    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left
    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left
    - overflow
    - overflow-x
    - overflow-y
    - -ms-overflow-x
    - -ms-overflow-y
    - -webkit-overflow-scrolling
    - clip
    - clear
    - font
    - font-family
    - font-size
    - font-style
    - font-weight
    - line-height
    - letter-spacing
    - word-spacing
    - color
    - text-align
    - text-decoration
    - text-indent
    - text-overflow
    - text-rendering
    - text-size-adjust
    - text-shadow
    - text-transform
    - word-break
    - word-wrap
    - white-space
    - vertical-align
    - list-style
    - list-style-type
    - list-style-position
    - list-style-image
    - pointer-events
    - cursor
    - background
    - background-attachment
    - background-color
    - background-image
    - background-position
    - background-repeat
    - background-size
    - border
    - border-color
    - border-image
    - border-spacing
    - border-style
    - border-width
    - -webkit-border-radius
    - -moz-border-radius
    - border-radius
    - -webkit-border-top-left-radius
    - -moz-border-radius-topleft
    - border-top-left-radius
    - -webkit-border-top-right-radius
    - -moz-border-radius-topright
    - border-top-right-radius
    - -webkit-border-bottom-right-radius
    - -moz-border-radius-bottomright
    - border-bottom-right-radius
    - -webkit-border-bottom-left-radius
    - -moz-border-radius-bottomleft
    - border-bottom-left-radius
    - content
    - quotes
    - outline
    - outline-offset
    - opacity
    - filter
    - visibility
    - size
    - zoom
    - -webkit-user-select
    - -moz-user-select
    - -ms-user-select
    - user-select
    - nav-index
    - nav-up
    - nav-right
    - nav-down
    - nav-left
    - -webkit-transition
    - -moz-transition
    - -ms-transition
    - -o-transition
    - transition
    - -webkit-transition-delay
    - -moz-transition-delay
    - -ms-transition-delay
    - -o-transition-delay
    - transition-delay
    - -webkit-transition-timing-function
    - -moz-transition-timing-function
    - -ms-transition-timing-function
    - -o-transition-timing-function
    - transition-timing-function
    - -webkit-transition-duration
    - -moz-transition-duration
    - -ms-transition-duration
    - -o-transition-duration
    - transition-duration
    - -webkit-transition-property
    - -moz-transition-property
    - -ms-transition-property
    - -o-transition-property
    - transition-property
    - -webkit-transform
    - -moz-transform
    - -ms-transform
    - -o-transform
    - transform
    - -webkit-transform-origin
    - -moz-transform-origin
    - -ms-transform-origin
    - -o-transform-origin
    - transform-origin
    - -webkit-animation
    - -moz-animation
    - -ms-animation
    - -o-animation
    - animation
    - -webkit-animation-name
    - -moz-animation-name
    - -ms-animation-name
    - -o-animation-name
    - animation-name
    - -webkit-animation-duration
    - -moz-animation-duration
    - -ms-animation-duration
    - -o-animation-duration
    - animation-duration
    - -webkit-animation-play-state
    - -moz-animation-play-state
    - -ms-animation-play-state
    - -o-animation-play-state
    - animation-play-state
    - -webkit-animation-timing-function
    - -moz-animation-timing-function
    - -ms-animation-timing-function
    - -o-animation-timing-function
    - animation-timing-function
    - -webkit-animation-delay
    - -moz-animation-delay
    - -ms-animation-delay
    - -o-animation-delay
    - animation-delay
    - -webkit-animation-iteration-count
    - -moz-animation-iteration-count
    - -ms-animation-iteration-count
    - -o-animation-iteration-count
    - animation-iteration-count
    - -webkit-animation-iteration-count
    - -moz-animation-iteration-count
    - -ms-animation-iteration-count
    - -o-animation-iteration-count
    - animation-iteration-count
    - -webkit-animation-direction
    - -moz-animation-direction
    - -ms-animation-direction
    - -o-animation-direction
    - animation-direction
    - box-align
    - box-flex
    - box-orient
    - box-pack
    - -webkit-box-shadow
    - -moz-box-shadow
    - box-shadow
    - -webkit-box-sizing
    - -moz-box-sizing
    - box-sizing
    - table-layout
    - animation
    - background-clip
    - backface-visibility
    - resize
    - appearance
    - user-select
    - direction
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false

  PropertySpelling:
    enabled: true
    extra_properties: []
    disabled_properties: []

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  PseudoElement:
    enabled: false

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false

  SelectorDepth:
    enabled: false
    max_depth: 3

  SelectorFormat:
    enabled: false
    convention: hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'

  SpaceAfterComment:
    enabled: false
    style: one_space # or 'no_space', or 'at_least_one_space'
    allow_empty_comments: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: true
    style: one_space # or 'no_space', 'at_least_one_space' or 'one_space_or_newline'

  SpaceAfterVariableName:
    enabled: false

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'at_least_one_space', or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: false

  TransitionAll:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
